services:
  spring:
    image: 'devcorpecu/spring-factura:0.1'

    container_name: spring
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://proyectoups.postgres.database.azure.com:5432/factura
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Cris123.
  angular:
    image: 'devcorpecu/front-factura:0.1'
    container_name: angular
    ports:
      - "80:80"
    depends_on:
      - spring